package com.pyg_pojo.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbPromotion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.id
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.active_scope
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private String activeScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.description
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.start_date
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.end_date
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.status
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.title
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.title_img
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    private String titleImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.id
     *
     * @return the value of tb_promotion.id
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.id
     *
     * @param id the value for tb_promotion.id
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.active_scope
     *
     * @return the value of tb_promotion.active_scope
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public String getActiveScope() {
        return activeScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.active_scope
     *
     * @param activeScope the value for tb_promotion.active_scope
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setActiveScope(String activeScope) {
        this.activeScope = activeScope == null ? null : activeScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.description
     *
     * @return the value of tb_promotion.description
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.description
     *
     * @param description the value for tb_promotion.description
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.start_date
     *
     * @return the value of tb_promotion.start_date
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.start_date
     *
     * @param startDate the value for tb_promotion.start_date
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.end_date
     *
     * @return the value of tb_promotion.end_date
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.end_date
     *
     * @param endDate the value for tb_promotion.end_date
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.status
     *
     * @return the value of tb_promotion.status
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.status
     *
     * @param status the value for tb_promotion.status
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.title
     *
     * @return the value of tb_promotion.title
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.title
     *
     * @param title the value for tb_promotion.title
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.title_img
     *
     * @return the value of tb_promotion.title_img
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public String getTitleImg() {
        return titleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.title_img
     *
     * @param titleImg the value for tb_promotion.title_img
     *
     * @mbggenerated Tue Apr 02 13:07:31 CST 2019
     */
    public void setTitleImg(String titleImg) {
        this.titleImg = titleImg == null ? null : titleImg.trim();
    }
}