package com.pyg_dao.mapper;

import com.pyg_pojo.pojo.TbSeckillOrder;
import com.pyg_pojo.pojo.TbSeckillOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbSeckillOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int countByExample(TbSeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int deleteByExample(TbSeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int insert(TbSeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int insertSelective(TbSeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    List<TbSeckillOrder> selectByExample(TbSeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    TbSeckillOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") TbSeckillOrder record, @Param("example") TbSeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int updateByExample(@Param("record") TbSeckillOrder record, @Param("example") TbSeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int updateByPrimaryKeySelective(TbSeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbggenerated Tue Apr 02 10:26:13 CST 2019
     */
    int updateByPrimaryKey(TbSeckillOrder record);
}